set nocompatible             " 关闭兼容模式
"execute pathogen#infect()
syntax on                    " 开启文件类型侦测
syntax enable                " 打开语法高亮
set ic                      "忽略大小写
colo desert                 "颜色方案
set encoding=utf-8          "设置编码格式
set guifont=Monospace\ 14   "设置字体
set incsearch               "打开搜索时匹配高亮
set showcmd                 "设置右下角显示输入的命令
" for ruby
set tabstop=2                " 设置tab键的宽度
set softtabstop=2             "一旦设置了softtabstop的值时，你按下tab键，插入的是空格和tab制表符的混合
set shiftwidth=2             " 用于程序中自动缩进所使用的空白长度
set expandtab                 "不允许在代码使用TAB符，而以4个空格代之
set autoindent               " 自动对齐
set cindent shiftwidth=2     " 自动缩进4空格
set smartindent              " 智能自动缩进
set ai!                      " 设置自动缩进
set nu!                      " 显示行号
"set mouse=a                  " 启用鼠标
set ruler                    " 右下角显示光标位置的状态行
set hlsearch                 " 开启高亮显示结果
set nowrapscan               " 搜索到文件两端时不重新搜索
set vb t_vb=                 " 关闭提示音
set hidden                   " 允许在有未保存的修改时切换缓冲区
set list                     " 显示Tab符，使用一高亮竖线代替
set listchars=tab:\|\ ,
filetype on                 " Enable filetype detection
filetype indent on           " 针对不同的文件类型采用不同的缩进格式
filetype plugin on           " 针对不同的文件类型加载对应的插件
filetype plugin indent on    " 启用自动补全
"if has("autocmd") && exists("+omnifunc")
"    autocmd Filetype *
"            \    if &omnifunc == "" |
"            \        setlocal omnifunc=syntaxcomplete#Complete |
"            \    endif
"endif
